image: node:alpine
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - ~/.npm
    - .jest
stages:
  - deploy
before_script:
  - npm install --global expo-cli
  - npm ci
expo-deployments:
  stage: deploy
  script:
    - apk add --no-cache bash
    - npx expo login -u "norbertomat" -p "TNG!5f27JiAm*n/"
    - npx expo publish --non-interactive