image: node:alpine

stages:
  - write
  - read
  - generate
  - deploy

.before_script_template:
  before_script:
    - npm install --global expo-cli eas-cli
    - npm ci --cache .npm --prefer-offline
    - npx expo login -u $EXPO_USERNAME -p $EXPO_PASSWORD

write-to-file:
  stage: write
  script:
    - echo "pkasjbdlasj" >> apk.txt

read-from-file:
  stage: read
  script:
    - cat apk.txt

generate-link-to-expo:
  extends: .before_script_template
  stage: generate
  script:
    - npx expo publish --non-interactive > expo-link-output.txt
    - echo $( tail -n 1 expo-link-output.txt ) > expo-link.txt
  artifacts:
    paths:
      - expo-link.txt

generate-apk:
  extends: .before_script_template
  stage: generate
  script:
    - apk add --no-cache bash
    - EAS_NO_VCS=1 npx eas-cli build -p android --profile preview > apk-output.txt
    - echo $( tail -n 1 apk-output.txt ) > apk.txt
  artifacts:
    paths:
      - apk.txt

deploy-to-heroku:
  stage: deploy
  script:
    - cat expo-link.txt
    - cat apk.txt