image: node:alpine

stages:
  - publish
  - generate

.before_script_template:
  before_script:
    - npm install --global expo-cli eas-cli
    - npm ci --cache .npm --prefer-offline
    - npx expo login -u $EXPO_USERNAME -p $EXPO_PASSWORD

publish-to-expo:
  extends: .before_script_template
  stage: publish
  script:
    - echo "please work" > test.txt
    #- npx expo publish --non-interactive
  artifacts:
    paths:
      - test.txt

generate-apk:
  extends: .before_script_template
  stage: generate
  script:
    - cat test.txt
    #- apk add --no-cache bash
    #- EAS_NO_VCS=1 npx eas-cli build -p android --profile preview > apk.txt
    #- echo $( tail -n 1 apk.txt )