android-deploy:
  stage: build
  image: node:alpine
  only:
    - staging
    - master
  script:
    - npm install --global expo-cli eas-cli > test.txt
    - cat test.txt
    - echo $( tail -n 1 apk.txt )
    - npm ci --cache .npm --prefer-offline
    - apk add --no-cache bash
    - npx expo login -u $EXPO_USERNAME -p $EXPO_PASSWORD
    #- EAS_NO_VCS=1 npx eas-cli build -p android --profile preview > apk.txt