image: node:alpine

stages:
  - publish
  - generate

before_script:
  - npm install --global expo-cli eas-cli
  - npm ci --cache .npm --prefer-offline
  - npx expo login -u $EXPO_USERNAME -p $EXPO_PASSWORD

publish-to-expo:
  stage: publish
  script:
    - npx expo publish --non-interactive

generate-apk:
  stage: generate
  script:
    - apk add --no-cache bash
    - EAS_NO_VCS=1 npx eas-cli build -p android --profile preview > apk.txt
    - echo $( tail -n 1 apk.txt )