image: node:alpine
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - ~/.npm

stages:
  - deploy
before_script:
  - npm install --global expo-cli eas-cli
  - npm ci --cache .npm --prefer-offline
expo-deployments:
  stage: deploy
  script:
    - apk add --no-cache bash
    - npx expo login -u "norbertomat" -p "TNG!5f27JiAm*n/"
    #- npx expo publish --non-interactive
    - EAS_NO_VCS=1 npx eas-cli build -p android --profile preview