image: node:alpine

stages:
  - build
  - deploy

install-cli:
  stage: build
  script:
    - npm install --global expo-cli eas-cli
    - npm ci --cache .npm --prefer-offline
    - npx expo login -u $EXPO_USERNAME -p $EXPO_PASSWORD

generate-apk:
  stage: build
  script:
    - apk add --no-cache bash
    - EAS_NO_VCS=1 npx eas-cli build -p android --profile preview > apk.txt
    - echo $( tail -n 1 apk.txt )

publish-to-expo:
  stage: deploy
  script:
    - npx expo publish --non-interactive

